version: "3"

tasks:
  install:
    desc: "Installs the project dependencies and tools required for development"
    cmds:
      - go mod tidy
      - go mod download
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest

  build:
    desc: "Builds the project"
    cmds:
      - task: wails build

  dev:
    desc: "Starts the project in development mode"
    cmds:
      - task: wails dev

  test:
    desc: "Runs unit tests"
    cmds:
      - go test ./...      
  
  lint:
    desc: "Lints the project"
    cmds:
      - golangci-lint run ./... --fix
      - bun run --cwd ui lint

  format:
    desc: "Formats the project"
    cmds:
      - go fmt ./...
      - bun run --cwd ui format