version: "3"

tasks:
  install:
    desc: "Install project dependencies and tools required for development"
    cmds:
      - go mod tidy
      - go mod download
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install -v github.com/wailsapp/wails/v3/cmd/wails3@latest

  build:
    desc: "Build the project"
    cmds:
      - task: "{{OS}}:build"

  dev:
    desc: "Start the project in development mode"
    cmds:
      - task: "{{OS}}:run"

  test:
    desc: "Run unit tests"
    cmds:
      - go test ./...      
  
  lint:
    desc: "Lint the project"
    cmds:
      - golangci-lint run ./... --fix
      - bun run --cwd ui lint

  format:
    desc: "Format the project"
    cmds:
      - go fmt ./...
      - bun run --cwd ui format